[platformio]
; Default environment (most common)
default_envs = esp32

[env]
platform = espressif32
framework = arduino
monitor_speed = 115200

lib_deps =
  knolleary/PubSubClient@^2.8
  tzapu/WiFiManager@^2.0.17


; ESP32 – all ESP32 family boards
[env:esp32]
board = esp32dev


; ESP32-S2 – all S2 family boards
[env:esp32-s2]
board = esp32-s2-saola-1


; ESP32-S3 – all S3 family boards
[env:esp32-s3]
board = esp32-s3-devkitm-1


; ESP32-C3 – all C3 family boards
[env:esp32-c3]
board = esp32-c3-devkitm-1
