; IMPORTANT:
; This firmware targets generic ESP32 dev boards.
; If the device boot-loops or WiFi portal does not appear,
; you likely selected the wrong board type.
; Re-flash using a board profile matching your hardware.

[platformio]
default_envs = esp32

[env]
platform = espressif32@^6.13.0
framework = arduino
monitor_speed = 115200

; safer universal settings
board_build.flash_mode = dio
board_build.flash_freq = 40000000L
board_build.partitions = default.csv
board_upload.flash_size = 4MB
board_build.f_cpu = 160000000L

lib_deps = 
    jnthas/Improv WiFi Library@^0.0.4
    knolleary/PubSubClient@^2.8

; ESP32 – all ESP32 family boards
[env:esp32]
board = esp32dev
build_flags = 

; ESP32-S2 – all S2 family boards
[env:esp32-s2]
board = esp32-s2-saola-1
build_flags = 

; ESP32-S3 – all S3 family boards
[env:esp32-s3]
board = esp32-s3-devkitc-1
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1 
    
; ESP32-C3 – all C3 family boards
[env:esp32-c3]
board = esp32-c3-devkitm-1
build_flags = 
    -D ARDUINO_USB_MODE=1
    -D ARDUINO_USB_CDC_ON_BOOT=1     
